### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by AlecRomine** [yetanalytics/datasim-ui#3]
Started with an Ubuntu 16.04 VM with node(12.8.1), Java(openSDK 1.8), and Clojure (1.10.1) installed. and then ran
`sudo clojure -A:fig`  and got the output 
 ```Cloning: git@github.com:yetanalytics/re-codemirror.git
Error building classpath. connector is not available: 
com.jcraft.jsch.agentproxy.AgentProxyException: connector is not available: 
	at com.jcraft.jsch.agentproxy.ConnectorFactory.createConnector(ConnectorFactory.java:120)
	at clojure.tools.gitlibs.impl$fn__991.invokeStatic(impl.clj:30)
	at clojure.tools.gitlibs.impl$fn__991.invoke(impl.clj:28)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2320)
	at clojure.core$deref.invoke(core.clj:2306)
	at clojure.tools.gitlibs.impl$call_with_auth.invokeStatic(impl.clj:49)
	at clojure.tools.gitlibs.impl$call_with_auth.invoke(impl.clj:41)
	at clojure.tools.gitlibs.impl$git_clone_bare.invokeStatic(impl.clj:71)
	at clojure.tools.gitlibs.impl$git_clone_bare.invoke(impl.clj:68)
	at clojure.tools.gitlibs.impl$ensure_git_dir.invokeStatic(impl.clj:110)
	at clojure.tools.gitlibs.impl$ensure_git_dir.invoke(impl.clj:100)
	at clojure.tools.gitlibs$resolve.invokeStatic(gitlibs.clj:33)
	at clojure.tools.gitlibs$resolve.invoke(gitlibs.clj:29)
	at clojure.tools.gitlibs$procure.invokeStatic(gitlibs.clj:47)
	at clojure.tools.gitlibs$procure.invoke(gitlibs.clj:41)
	at clojure.tools.deps.alpha.extensions.git$eval1058$fn__1060.invoke(git.clj:42)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:209)
	at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:186)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:280)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:255)
	at clojure.tools.deps.alpha.script.make_classpath2$create_classpath.invokeStatic(make_classpath2.clj:57)
	at clojure.tools.deps.alpha.script.make_classpath2$create_classpath.invoke(make_classpath2.clj:49)
	at clojure.tools.deps.alpha.script.make_classpath2$run_core.invokeStatic(make_classpath2.clj:95)
	at clojure.tools.deps.alpha.script.make_classpath2$run_core.invoke(make_classpath2.clj:74)
	at clojure.tools.deps.alpha.script.make_classpath2$run.invokeStatic(make_classpath2.clj:116)
	at clojure.tools.deps.alpha.script.make_classpath2$run.invoke(make_classpath2.clj:110)
	at clojure.tools.deps.alpha.script.make_classpath2$_main.invokeStatic(make_classpath2.clj:161)
	at clojure.tools.deps.alpha.script.make_classpath2$_main.doInvoke(make_classpath2.clj:133)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:514)
	at clojure.main$main_opt.invoke(main.clj:510)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
```

**Comment by cliffcaseyyet** [comment]
@AlecRomine,

Please confirm if it now builds with this branch: https://github.com/yetanalytics/datasim-ui/tree/https-codemirror-dep

Thanks,
-Cliff

**Comment by AlecRomine** [comment]
This works great thanks!
